name: "task-manager"

services:
  db:
    container_name: task-manager
    build:
      context: .
      dockerfile: pgvector.dockerfile
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5433:5432
    restart: always

volumes:
  postgres_data:
